name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
      with:
        repository: mind4yottadb/mind-demo-server
        #token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
        path: demo-server
        run: docker image build --build-arg SERVERMODE=server-test --build-arg BRANCH=${{ github.event.inputs.source_branch }} --progress=plain -t mind-server .
