name: M test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pull-build-execute:
    runs-on: ubuntu-latest
    steps:
    - name: pull
      uses: actions/checkout@v4
      with:
        repository: mind4yottadb/mind-demo-server
        ref: main
        path: mind-demo-server


    - name: build-and-execute
      run: |
        cd mind-demo-server
        docker image build --build-arg SERVERMODE=server-test --build-arg BRANCH=${{ github.head_ref }} --progress=plain -t mind-server .
        docker run --init --tty -p 10000:10000 --name=mind-server mind-server
