name: M test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull the mind-demo-server
      uses: actions/checkout@v4
      with:
        repository: mind4yottadb/mind-demo-server
        ref: main
        path: demo-server

    - name: "Build the Docker image"
      run: |
        cd /home/runner/work/mind-server/mind-server/demo-server
        docker image build --build-arg SERVERMODE=server-test --build-arg BRANCH=main --progress=plain -t mind-server .
        docker run --init --tty -p 10000:10000 --name=mind-server mind-server
      working-directory: /home/runner/work/mind-server/mind-server/demo-server
