name: M test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pull-build-execute:
    runs-on: ubuntu-latest
    steps:
    - name: pull
      uses: actions/checkout@v4
      with:
        repository: mind4yottadb/mind-demo-server
        ref: main
        path: /home/runner/work/_temp/mind-demo-server

    steps:
      - name: build-and-execute
      run: |
        cd /home/runner/work/mind-server/mind-server/demo-server
        ls
        docker image build --build-arg SERVERMODE=server-test --build-arg BRANCH=v0.30.0 --progress=plain -t mind-server .
        docker run --init --tty -p 10000:10000 --name=mind-server mind-server
      working-directory: /home/runner/work/_temp/mind-demo-server
